# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioninos', '0003_nino_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nino',
            name='historia',
            field=models.TextField(max_length=1000),
        ),
    ]
