# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioninos', '0004_auto_20171005_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='historia',
            field=models.TextField(max_length=1500),
        ),
    ]
