# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioninos', '0006_auto_20171005_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='etapa',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Básico', 'Básico'), ('Diversificado', 'Diversificado')], max_length=15),
        ),
    ]
