# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import sitioninos.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioninos', '0007_auto_20171005_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=sitioninos.models.upload_location),
        ),
    ]
